In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv('./data/20230103/AIR_HOUR_2021.csv', encoding = 'cp949')

In [5]:
df = df.astype({'측정일시':'str'})

In [6]:
df.dtypes

측정일시            object
측정소 코드           int64
측정항목 코드          int64
평균값            float64
측정기 상태           int64
국가 기준초과 구분       int64
지자체 기준초과 구분      int64
저장일시             int64
dtype: object

In [7]:
df['측정일시'] = pd.to_datetime(df['측정일시'])

In [8]:
df

,측정일시,측정소 코드,측정항목 코드,평균값,측정기 상태,국가 기준초과 구분,지자체 기준초과 구분,저장일시
0,2021-12-31 23:00:00,108,5,0.700,0,0,0,20220101000024
1,2021-12-31 23:00:00,108,6,0.018,0,0,0,20220101000024
2,2021-12-31 23:00:00,108,8,19.000,0,0,0,20220101000024
3,2021-12-31 23:00:00,108,9,8.000,0,0,0,20220101000024
4,2021-12-31 23:00:00,103,3,0.018,0,0,0,20220101000025
...,...,...,...,...,...,...,...,...
1313995,2021-01-01 00:00:00,124,3,0.024,0,0,0,20210101010014
1313996,2021-01-01 00:00:00,124,1,0.003,0,0,0,20210101010014
1313997,2021-01-01 00:00:00,124,5,0.500,0,0,0,20210101010014
1313998,2021-01-01 00:00:00,124,6,0.021,0,0,0,20210101010014
1313999,2021-01-01 00:00:00,124,8,18.000,0,0,0,20210101010014

In [9]:
df.set_index('측정일시')

,측정소 코드,측정항목 코드,평균값,측정기 상태,국가 기준초과 구분,지자체 기준초과 구분,저장일시
측정일시,,,,,,,
2021-12-31 23:00:00,108,5,0.700,0,0,0,20220101000024
2021-12-31 23:00:00,108,6,0.018,0,0,0,20220101000024
2021-12-31 23:00:00,108,8,19.000,0,0,0,20220101000024
2021-12-31 23:00:00,108,9,8.000,0,0,0,20220101000024
2021-12-31 23:00:00,103,3,0.018,0,0,0,20220101000025
...,...,...,...,...,...,...,...
2021-01-01 00:00:00,124,3,0.024,0,0,0,20210101010014
2021-01-01 00:00:00,124,1,0.003,0,0,0,20210101010014
2021-01-01 00:00:00,124,5,0.500,0,0,0,20210101010014
2021-01-01 00:00:00,124,6,0.021,0,0,0,20210101010014
2021-01-01 00:00:00,124,8,18.000,0,0,0,20210101010014

In [10]:
df.to_csv('./update_python.csv', header = False, index = False)