# 소방청 타지역 검색

In [7]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from tqdm.notebook import tqdm

In [8]:
url = 'https://www.nfa.go.kr/nfa/introduce/status/firestationidfo/?searchDistance=10&searchMode=distance&myX=37.5605672&myY=126.9433486&searchKeyword='
driver = webdriver.Chrome('chromedriver')
driver.get(url)
time.sleep(2)

In [9]:
driver.find_element(By.ID,'searchKeyword').send_keys('광주')
driver.find_element(By.ID,'fsSearchBtn').click() # id = # 안붙여도됨.

In [28]:
soup = BeautifulSoup(driver.page_source, 'html.parser')
sta = soup.select('.stations-list > li')

In [29]:
st = sta[0]
st

<li id="0" style="">
<img class="marker" src="/resources/img/firestation/map_ic_119.png"/>
<span class="title">광산소방서_광주-평동-119 안전센터</span>
<address>광주광역시 광산구 월전동 1251</address>
<span class="tel">전화공사중</span>
<span class="info">광주소방안전본부</span>
</li>

In [30]:
# 관서명
name = st.select_one('.title').get_text()
# 주소
addr = st.select_one('address').get_text()
# 전화번호
tel = st.select_one('.tel').get_text()

In [31]:
print(name, addr, tel)

광산소방서_광주-평동-119 안전센터 광주광역시 광산구 월전동 1251 전화공사중

In [32]:
lines = []
for st in sta:
    name = st.select_one('.title').get_text()
    addr = st.select_one('address').get_text()
    tel = st.select_one('.tel').get_text()
    lines.append([name, addr, tel])
df = pd.DataFrame(lines, columns = ['관서명', '주소', '전화번호'])

In [33]:
df

                    관서명                            주소          전화번호
0  광산소방서_광주-평동-119 안전센터            광주광역시 광산구 월전동 1251         전화공사중
1  광산소방서_광주-첨단-119 안전센터  광주광역시 광산구 임방울대로825번길 16(쌍암동)  062-606-4883
2  광산소방서_광주-신가-119 안전센터        광주광역시 광산구 수등로 236(신가동)  062-606-4863
3  광산소방서_광주-비아-119 안전센터     광주광역시 광산구 비아로12번길 10(비아동)  062-606-4843
4  광산소방서_광주-월곡-119 안전센터        광주광역시 광산구 사암로 276(월곡동)  062-606-4823
5  광산소방서_광주-송정-119 안전센터      광주광역시 광산구 상무대로 93-1(도산동)  062-606-4803
6  광산소방서_광주-하남-119 안전센터     광주광역시 광산구 하남산단1번로 13(하남동)  062-606-4903
7  북부소방서_광주-동림-119 안전센터        광주광역시 북구 북문대로 202(동림동)  062-606-4783
8  북부소방서_광주-두암-119 안전센터           광주광역시 북구 삼정로 5(두암동)  062-606-4763
9  북부소방서_광주-일곡-119 안전센터         광주광역시 북구 설죽로 529(일곡동)  062-606-4743

In [35]:
driver.find_element(By.CSS_SELECTOR,'.next_page > a').click()
time.sleep(2)

In [36]:
lines = []
for st in sta:
    name = st.select_one('.title').get_text()
    addr = st.select_one('address').get_text()
    tel = st.select_one('.tel').get_text()
    lines.append([name, addr, tel])
df2 = pd.DataFrame(lines, columns = ['관서명', '주소', '전화번호'])

In [37]:
driver.find_element(By.CSS_SELECTOR,'.next_page > a').click()
time.sleep(2)
lines = []
for st in sta:
    name = st.select_one('.title').get_text()
    addr = st.select_one('address').get_text()
    tel = st.select_one('.tel').get_text()
    lines.append([name, addr, tel])
df3 = pd.DataFrame(lines, columns = ['관서명', '주소', '전화번호'])

In [39]:
total_df= pd.concat([df, df2, df3])

In [40]:
total_df

                    관서명                            주소          전화번호
0  광산소방서_광주-평동-119 안전센터            광주광역시 광산구 월전동 1251         전화공사중
1  광산소방서_광주-첨단-119 안전센터  광주광역시 광산구 임방울대로825번길 16(쌍암동)  062-606-4883
2  광산소방서_광주-신가-119 안전센터        광주광역시 광산구 수등로 236(신가동)  062-606-4863
3  광산소방서_광주-비아-119 안전센터     광주광역시 광산구 비아로12번길 10(비아동)  062-606-4843
4  광산소방서_광주-월곡-119 안전센터        광주광역시 광산구 사암로 276(월곡동)  062-606-4823
5  광산소방서_광주-송정-119 안전센터      광주광역시 광산구 상무대로 93-1(도산동)  062-606-4803
6  광산소방서_광주-하남-119 안전센터     광주광역시 광산구 하남산단1번로 13(하남동)  062-606-4903
7  북부소방서_광주-동림-119 안전센터        광주광역시 북구 북문대로 202(동림동)  062-606-4783
8  북부소방서_광주-두암-119 안전센터           광주광역시 북구 삼정로 5(두암동)  062-606-4763
9  북부소방서_광주-일곡-119 안전센터         광주광역시 북구 설죽로 529(일곡동)  062-606-4743
0  광산소방서_광주-평동-119 안전센터            광주광역시 광산구 월전동 1251         전화공사중
1  광산소방서_광주-첨단-119 안전센터  광주광역시 광산구 임방울대로825번길 16(쌍암동)  062-606-4883
2  광산소방서_광주-신가-119 안전센터        광주광역시 광산구 수등로 236(신가동)  062-606-4863
3  광산소방서_광주-비아-119 안전센터     광주광역시 광산구 비아로12번길 10(비아동)  062-606-4843
4  광산소방서_광주-월곡-119 안전센터        광주광역시 광산구 사암로 276(월곡동)  062-606-4823
5  광산소방서_광주-송정-119 안전센터      광주광역시 광산구 상무대로 93-1(도산동)  062-606-4803
6  광산소방서_광주-하남-119 안전센터     광주광역시 광산구 하남산단1번로 13(하남동)  062-606-4903
7  북부소방서_광주-동림-119 안전센터        광주광역시 북구 북문대로 202(동림동)  062-606-4783
8  북부소방서_광주-두암-119 안전센터           광주광역시 북구 삼정로 5(두암동)  062-606-4763
9  북부소방서_광주-일곡-119 안전센터         광주광역시 북구 설죽로 529(일곡동)  062-606-4743
0  광산소방서_광주-평동-119 안전센터            광주광역시 광산구 월전동 1251         전화공사중
1  광산소방서_광주-첨단-119 안전센터  광주광역시 광산구 임방울대로825번길 16(쌍암동)  062-606-4883
2  광산소방서_광주-신가-119 안전센터        광주광역시 광산구 수등로 236(신가동)  062-606-4863
3  광산소방서_광주-비아-119 안전센터     광주광역시 광산구 비아로12번길 10(비아동)  062-606-4843
4  광산소방서_광주-월곡-119 안전센터        광주광역시 광산구 사암로 276(월곡동)  062-606-4823
5  광산소방서_광주-송정-119 안전센터      광주광역시 광산구 상무대로 93-1(도산동)  062-606-4803
6  광산소방서_광주-하남-119 안전센터     광주광역시 광산구 하남산단1번로 13(하남동)  062-606-4903
7  북부소방서_광주-동림-119 안전센터        광주광역시 북구 북문대로 202(동림동)  062-606-4783
8  북부소방서_광주-두암-119 안전센터           광주광역시 북구 삼정로 5(두암동)  062-606-4763
9  북부소방서_광주-일곡-119 안전센터         광주광역시 북구 설죽로 529(일곡동)  062-606-4743